# Generated by Django 2.0.4 on 2018-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_node', '0002_auto_20180426_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
