# Generated by Django 2.0.4 on 2018-05-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_node', '0003_auto_20180426_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group_relation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Registered_Users',
        ),
    ]
